### ISSUE TITLE
reminder feature

### ISSUE THREAD

**Issue by jidicula** [idoneam/Canary#1]
Implement a RemindMe! feature for the bot so we have reminders.

**Comment by idodin** [comment]
I'll grab this if no one is working on it? Very straight-forward to implement.

**Comment by idodin** [comment]
Planned frequencies for reminders:

- [ ] Daily
- [ ] Weekly
- [ ] Monthly

**Comment by idodin** [comment]
Resolved in #64. Closing this :)
