### ISSUE TITLE
CFIA recalls

### ISSUE THREAD

**Issue by jidicula** [idoneam/Canary#122]
### CFIA recall notices:
The Canadian Food Inspection Agency regularly publishes notices about food recalls related to food safety as well as allergen contamination. These are aggregated in RSS feeds: http://inspection.gc.ca/about-the-cfia/newsroom/web-feeds/eng/1301594387046/1301595515800 .

### Parse RSS feed:
Use a Python (or 3rd-party) library to track the feed and post any new notices in the server.

**Comment by davidlougheed** [comment]
done!
