### ISSUE TITLE
Urban HTML decoding

### ISSUE THREAD

**Issue by jidicula** [idoneam/Canary#13]
# Bug Report: urban HTML decoding

### Bug Description
Not decoding HTML escape sequences.

### Reproduction Steps
*Steps to reproduce the behavior, for example:*
1. Go to any channel.
2. Send ?urban [any query which has a definition containing an HTML escape sequence]
3. Marty responds with a definition including &amp; &apos; etc

### Potential Reasons behind Bug:
HTML escape sequences aren't decoded. Probably can fix with some BS4 tweaking but tbh I'm just trying to get a tshirt for hacktoberfest.

**Comment by trungams** [comment]
http://api.urbandictionary.com/v0/define?term={query}

Maybe just get rid of bs4 and use their API instead? This is way simpler and we can fetch multiple definitions too. Just be careful because there might be escape characters in the json

**Comment by jidicula** [comment]
Yeah, this is way better, I'll re-open the issue.

Johanan

**Comment by mjip** [comment]
We could also filter for definitions that are shorter than x number of characters, instead of spitting out the first one which can sometimes be a huge wall of text. Not directly related to this issue though.

**Comment by trungams** [comment]
We'll see how the new command looks and try to exclude the lengthy definitions if it happens. For now I'm closing this issue. Further information can be found in #19
