### ISSUE TITLE
Role-related functionality

### ISSUE THREAD

**Issue by dbenjaminmiller** [idoneam/Canary#136]
### Feature Description:
Make a substitute for .inrole, etc. to reduce nadeko dependency. I can probably do it myself when I get around to it.

### Implementation Suggestion:
I'll read the `discord.py` docs later.

**Comment by dbenjaminmiller** [comment]
The bot should be able to accept input of the type `?inrole a b …`, which will return a list of all users who are members of all the roles listed (for an arbitrary number of roles)

**Comment by idodin** [comment]
I can grab this one, unless you're excited about it :p

**Comment by dbenjaminmiller** [comment]
Go ahead

**Comment by le-potate** [comment]
Here are some other role-related command that Mosebot has:
-Auto assign a role to new users who join
-A command to make a role self-assignable (or stop it from being self-assignable), and a command that lets users give themselves the role.
-Get roles from emojis on a message (eg `.reaction CS:GO :some_emoji: R6 :some_emoji:` will add those emojis to the last message posted by the mod who called the command and people will get the roles when they click on it)
-Get the list of all roles and of all self-assignable roles

**Comment by lamminade** [comment]
this is going to require database stuff isnt it ?
role name -  self-assignable?

**Comment by idodin** [comment]
Yepp persist a mapping between emoji ID and role - ideally allow it to be dynamically configurable

**Comment by jidicula** [comment]
Bump

**Comment by le-potate** [comment]
Things left to do to close this:
- A command to make a role self-assignable (or stop it from being self-assignable) (requires converting ?iam to use db)
- Auto-assign roles from emojis on a message

Mose also had a function to auto-assign a role to new users who join, I've never seen this feature asked for on the server so this issue could be closed without this, but it could be useful.

**Comment by le-potate** [comment]
I will move the last comment from 2020 into its own issue given that its a big change
