### ISSUE TITLE
TikZ

### ISSUE THREAD

**Issue by dbenjaminmiller** [idoneam/Canary#143]
### Feature Description:

Canary could be used to draw TikZ figures, per suggestion.

**Comment by idodin** [comment]
Please leave more details about this function: what are the expected inputs? Outputs? Is this an intensive operation?

**Comment by dbenjaminmiller** [comment]
The way to do this would most likely be as follows:

(1) the user would input in the form ?tikz … and the rest of the message would be taken as tikz instructions.
(2) there would be a template, which would be a a barebones latex document using tikz-standalone (having a space in the middle for the figure in effect)
(3) pdflatex would be run on the document (dvipng + latex has some deficiencies with tikz)
(4) imagemagick or similar would be used to convert the PDF to PNG
(5) the same operation that is currently done with OpenCV to add a border would be done.
(6) canary would send back the processed png as output

**Comment by le-potate** [comment]
@dbenjaminmiller Based on your comments on the server should this be closed?

**Comment by dbenjaminmiller** [comment]
Go ahead. wontfix unless I get a lot of free time and change my mind
