### ISSUE TITLE
Custom Reacts

### ISSUE THREAD

**Issue by le-potate** [idoneam/Canary#146]
Make the bot send a message when certain words are written

### Implementation Suggestion:
`?acr "ban" ":hammer:"` would make the bot send `:hammer:` when `ban` is written 
When the custom react is created, you receive an ID, e.g. 42. With it you can do
- `?crad 42` would delete the message that called the react (e.g. `ban`)
- `?crca 42` would activate the custom react if the words are anywhere in a message (e.g. `hey ban me` would work)
- `?crdm 42` would answer in dms (e.g. `:hammer:` would be sent in the DM of the person who wrote `ban`)
There should also be a way to list all the custom reacts and their IDs, and a way to delete them

### Other stuff to do
- Find out all the custom reacts that Mosebot was doing
- Remove the `MARTY_RESPONSES` in `main.py` and add them as custom reacts instead

**Comment by lazho** [comment]
Can we not pollute the namespace for commands with 4 different top level commands

Can we just do like `?cr add "string" "react"` and `?cr set id [auto-delete | anywhere | dm]`
