### ISSUE TITLE
Use embeds for quotes

### ISSUE THREAD

**Issue by jidicula** [idoneam/Canary#153]
### Description of Problem / Inefficiency:
Quotes is kind of janky for escaping pings.

### Implementation Suggestion:

Use Discord's embed feature to format quotes nicely. First line can be the date of the quote, 2nd line can be the content, and the bottom of the embed pane can have the quotee along with their avatar.

### Additional Context / Screenshots:
https://leovoel.github.io/embed-visualizer/

**Comment by dbenjaminmiller** [comment]
Seems done. For anything more, open a new issue.
