### ISSUE TITLE
[Enhancement] add boot command

### ISSUE THREAD

**Issue by dbenjaminmiller** [idoneam/Canary#161]
add ?boot command to allow for a pyramid of boots ... potentially of arbitrary height but a triforce to begin anyway. thanks to @davidlougheed for the idea

**Comment by jidicula** [comment]
It should take an integer argument for the number of pyramid levels. Kind of feels like an early COMP 202 assignment.

Johanan

**Comment by dbenjaminmiller** [comment]
Yeah, except one issue: perhaps there is a practical maximum considering display size: a pyramid with a very large base will come out an incomprehensible mess on most phone screens and, if large enough, even on the desktop.

**Comment by davidlougheed** [comment]
we can add a max limit, still think arbitrary height is fun
