### ISSUE TITLE
Automate backups of the db a little more

### ISSUE THREAD

**Issue by mjip** [idoneam/Canary#20]
# Enhancement Request: Backup automation

### Description of Problem / Inefficiency:
Currently, whoever's hosting marty will upload the db every once in a while. We've lost the most recent versions of the db before since this doesn't get done enough, so there's a need for this. 

### Implementation Suggestion:
Marty could have a ?backup command that will use send_file to upload the db to a channel just for db backups, or something. This would only get triggered if someone triggered it though, so it's not the most ideal solution. Another thing to try is to put the command on a timer, which makes it pretty hands-free but isn't very robust since if the server goes down and the bot needs to be restarted, it'll reset. Maybe implementing both options would be better.

**Comment by trungams** [comment]
been there done that

https://github.com/trungams/CommieBot/blob/fc59fe7ebc10ef11dd699f3f8a825bc77859c72e/main.py#L125

**Comment by mjip** [comment]
Then bring it here lol
