### ISSUE TITLE
See the list of users in a channel

### ISSUE THREAD

**Issue by le-potate** [idoneam/Canary#224]
### Feature Description:
Since the McGill server now has more than 1000 users, it is not possible to see a complete list of users in any channel anymore. 

### Implementation Suggestion:
It is important that only people in a certain channel can see the list of users in that channel. A way to do this would be a command `?inchannel` that sends the list of users in the channel itself. Another way would be a command `?inchannel #channel` that sends a DM to the person who called if they are in the channel.

**Comment by clu2001** [comment]
Hello I shall work on this thanks
