### ISSUE TITLE
Metro outages

### ISSUE THREAD

**Issue by mjip** [idoneam/Canary#23]
# Feature Request: Metro outages webhook 

### Feature Description:
Marty could scrape from either http://www.stm.info/en/info/service-updates/metro or one of the twitter accounts (they don't seem to regularly update however) to push notifications about when the metro is down to a specific channel. You could also do it by subscribing to SMS notifications using Twilio or another SMS API (seems to be the most reliable).

**Comment by ValerianClerc** [comment]
potential implementation:
*use STM email notifications and IFTTT (hooked up to gmail) to make discord webhook that posts service update emails in a discord channel?

https://www.reddit.com/r/discordapp/comments/6gfr4n/i_used_webhooks_to_create_a_notification_center/dis974c/

**Comment by jidicula** [comment]
- [ ] implement fetch function

- [ ] add output embed

- [ ] configure output channel
