### ISSUE TITLE
Purge Command

### ISSUE THREAD

**Issue by idodin** [idoneam/Canary#3]
# Feature Request: Purge Command

### Feature Description:
`?purge x` - Unverify McGillians who have been inactive for the past x days. Return list of purged members.

### Implementation Suggestion:
:x: Erroneous input :arrow_forward: Not an Integer
Grab users by McGillian role. For user who has been inactive for the past x days, remove McGillian Role. 

### Additional Context / Screenshots:
*n/a*

**Comment by trungams** [comment]
Closing because no progress has been made for a while. Feel free to reopen when this is brought up in mod discussion
