### ISSUE TITLE
Command argument parser util

### ISSUE THREAD

**Issue by trungams** [idoneam/Canary#46]
### Description of Problem / Inefficiency:
Similar to how python has argparse for parsing command line arguments, we can create a utility for parsing optional arguments from commands. Any command that uses optional arguments can take advantage of this utility.

### Implementation Suggestion:
When a command uses argparser, a parser object will be initialized. The Parser class provides functions like taking a string and returning a dictionary of parsed arguments. An optional argument can be registered using the object's nonstatic method. After reading the string and building a complete dictionary, the dictionary can be returned to the calling command.

Example usage:
```python
from utils import customargparse

async def command_name(ctx, *, query_string):
    parser = argparse.ArgParser()
    parser.register(argument, 
        type=int/str/float/whatever, 
        name='argument_name', 
        default_value=0/None/''
    )
    arguments = parser.parse(query_string)
    print(arguments[using_argument_name_as_key])
```

### Additional Context / Screenshots:
![Example command with optional arguments](https://user-images.githubusercontent.com/25715630/48380560-3ac8d500-e6a6-11e8-9d91-f4023d2c23f0.png)

**Comment by le-potate** [comment]
Similar parsing utility (with different implementation) done in #377
