### ISSUE TITLE
Category Appended to ?urban result

### ISSUE THREAD

**Issue by idodin** [idoneam/Canary#6]
# Bug Report: Category Appended to ?urban result

### Bug Description
There is a category appended to the ?urban response embed's title.

### Reproduction Steps
*Steps to reproduce the behavior, for example:*
1. Go to any channel.
2. Send ?urban <word>
3. Marty responds with: Embed with title: <word><category>

### Potential Reasons behind Bug:
:thinking: 

### Screenshots:
*To be added*

### Additional Context:
Kudos to @jidicula for pointing this out.

**Comment by trungams** [comment]
We're parsing JSON file instead of Html so the title looks good at the moment. For more info check #19
