### ISSUE TITLE
[Enhancement] spotify link reformatting

### ISSUE THREAD

**Issue by jidicula** [idoneam/Canary#74]
### Description of Problem / Inefficiency:
weird bug with the discord API that crashes the desktop app with certain spotify links.

### Implementation Suggestion:
can someone add a rule to marty to delete links of this form and repost the link identifying the user who posted it in the form `user: [spotify link]` within ticks so the spotify embedding isn't called?

### Additional Context / Screenshots:

This is the link format:
https://open.spotify.com/track/5HjEC3NlSzKsVKmqnhXrum?context=spotify%3Auser%%3Aplaylist%3A4PTJQnhzs5mo4wrKlTMlS4&si=RzHko2lIQMCSPDp0jubksgYou

**Comment by trungams** [comment]
Closing issue because discord fixed it for us
