### ISSUE TITLE
Override paginator module

### ISSUE THREAD

**Issue by trungams** [idoneam/Canary#75]
Example:
![image](https://user-images.githubusercontent.com/25715630/41944352-6629e958-7975-11e8-8110-2548b7eac3ee.png)

This is especially useful for listing anything.

Marty will send message in embed format instead of code blocks (looks neat), and will wait for users' reaction to that message to turn pages, instead of sending all pages at once.

Current implementation (discord.py default):
![image](https://user-images.githubusercontent.com/25715630/41944445-dcef95b0-7975-11e8-8a1a-bdd206c74313.png)

**Comment by idodin** [comment]
Resolved in #81 . Closing.
