### ISSUE TITLE
Reaction add event is never called

### ISSUE THREAD

**Issue by trungams** [idoneam/Canary#76]
We are currently using on_reaction_add() event. According the API reference however, the event is not called if the message does not exist in Client.messages cache. A fix would be to use on_raw_reaction_add() instead, since this event is always called regardless of cache (we don't need to know how discord.py works for this one)

![image](https://user-images.githubusercontent.com/25715630/42276595-5874c2a4-7f62-11e8-9780-0978b0277748.png)

We should also drop the current ranking, since it hasn't been working for a long time, and also we have downmartlet now ;)

**Comment by trungams** [comment]
https://discordpy.readthedocs.io/en/rewrite/api.html?highlight=client#discord.on_reaction_add

**Comment by idodin** [comment]
I thought we always had downmartlet? But yeah, I think a ranking reset is good :).
