### ISSUE TITLE
Add a poll feature/Figure out how to do it

### ISSUE THREAD

**Issue by le-potate** [idoneam/Canary#81]
### Feature Description:
Several members including the **_server owner_** have asked for an anonymous poll feature. However, we aren't quite sure how to implement it

### Implementation Suggestion:
- Since the classic Discord way to have polls is through emojis, the "familiar" way would be to count reacts and reset upon click. However, the time to make the reacts reset would be a problem if the poll is to be truly anonymous since people could see it during that time
- A better way would be to answer a DM from the bot. However, this might be a more annoying way.
- There could be multiple "versions", like a non-anonymous one that just removes emojis that aren't choices, etc.

**Comment by trungams** [comment]
<@!269208707068329994> ping pong

**Comment by le-potate** [comment]
<@!259549018781253632> pong ping

**Comment by le-potate** [comment]
Seems like discord will do it's own version/give more appropriate tools in the near future: see https://blog.discord.com/the-future-of-bots-on-discord-4e6e050ab52e and this demo: https://www.figma.com/proto/DDsdQLvBqmmPgZNgeNKmvf/Bot-Proposal?node-id=129%3A77&viewport=28579%2C-4007%2C6.748552322387695&scaling=min-zoom

I think for now this is wontfix, but this could be opened again if we get rid of Mose before those features are implemented by Discord
