### ISSUE TITLE
Make new quotes deletable by the person who quoted for a few minutes

### ISSUE THREAD

**Issue by le-potate** [idoneam/Canary#83]
### Feature Description:
Sometimes people add quotes and they makes typos, etc. and now if they want to correct it the person who was quoted must go and delete it which is annoying for them. The person who quotes should be able to delete the quote for a short while, somewhere between 1 or 5 minutes.

### Implementation Suggestion:
Put the 🚮 emoji on Marty's "Quote added." message that only the person who quoted can use (maybe the person who was quoted too?), and ask for confirmation

**Comment by trungams** [comment]
No

**Comment by le-potate** [comment]
done
