### ISSUE TITLE
Marty has internal errors when running stop_reminder and remindme without arguments

### ISSUE THREAD

**Issue by Yuyu-Ren** [idoneam/Canary#83]
# Bug Report: Marty has internal errors when running stop_reminder and remindme without arguments

### Bug Description
When running `?stop_reminder` or `?remindme` in a channel other than DMs, Marty does not reply.

### Reproduction Steps
*Steps to reproduce the behavior, for example:*
1. Go to any channel.
2. Send either `?stop_reminder` or `?remindme`
3. Marty responds with: *Absolutely Nothing.*

### Potential Reasons behind Bug:
Empty arguments when calling the aforementioned commands leads to an internal exception being thrown as Marty tries to deal with empty, undefined function parameters.

### Additional Context:
The functions in question under `db.py`:
```async def remindme(self, ctx, freq: str, *, quote: str):```
```async def stop_reminder(self, ctx, reminder: str):```

**Comment by idodin** [comment]
Resolved in #84. Closing.
