### ISSUE TITLE
[ODD BEHAVIOR] Removing older reminders decreases index counter

### ISSUE THREAD

**Issue by Yuyu-Ren** [idoneam/Canary#88]
# Bug Report:  Removing middle reminders decreases index counter
### Bug Description
When more than one reminder is added at the same time, removing the "oldest" reminder causes the index to decrease, causing stop_reminder to behave weirdly. 

### Reproduction Steps
1. Go to bot channel.
2. Send `?remindme daily message1` 
2. Send `?remindme daily message2`
3. Marty says you can cancel the reminders by entering the corresponding value.
4. Go to Marty's DM ;)
5. Send `?stop_reminder 1`
6. Send `?stop_reminder 2`
7. Marty will tell you to use `?stop_reminder` with a number between 1 and 1 (when logically it should be 2).

### Potential Reasons behind Bug:
Marty deletes the database entry specified which causes all the other reminders belonging to the user to "drop down". 

### Screenshots:
Setting up reminders:
![image](https://cdn.discordapp.com/attachments/470411486301388824/470815409885544458/unknown.png)
Deleting middle reminder (Results: 4, ~5~, 6)
![image](https://cdn.discordapp.com/attachments/470411486301388824/470815364662689792/unknown.png)
![image](https://user-images.githubusercontent.com/8889046/43058436-ed63212a-8e04-11e8-94f8-781366d6f484.png)
Notice that the 6th reminder (msg3) is now the 5th due to row deletion in DB, so no "6th" reminder to delete from other messages sent by Marty. To delete "msg3", we need to do `?stop_reminder 5`.

### Proposed Fixes:
Automatically print a table of reminders with updated counters as per issue #67

**Comment by idodin** [comment]
Closing this. Less of a bug and more of an enhancement which will be addressed in #67
