### ISSUE TITLE
[Enhancement] Add GPL license

### ISSUE THREAD

**Issue by davidlougheed** [idoneam/Canary#91]
We voted on Discord to add the GPL license to Canary. This needs the explicit approval of every contributor to the codebase. Please respond or react to this issue in approval, or say something if you disagree.

Contributors:
- [x] @trungams 
- [x] @jidicula 
- [x] @idodin 
- [x] @davidlougheed 
- [x] @mjip 
- [x] @Adoria 
- [ ] @jbby 
- [x] @Yuyu-Ren 
- [x] @lamminade 
- [x] @bbbxyz 
- [x] @demetrios-koziris 
- [x] @ValerianClerc 
- [x] @lazho

**Comment by trungams** [comment]
Why are we still waiting on a vote when the bot has already been claimed to be redistributable under GPL? Then this issue means nothing but an unnecessary formality

https://github.com/idoneam/Canary/blob/e4bb5495e33ce759daa29cc178e53217a424c72c/cogs/memes.py#L24

**Comment by jidicula** [comment]
Yeah, it's been over a month. Let's GPL it.
