### ISSUE TITLE
[Enhancement] Replace requests module by aiohttp

### ISSUE THREAD

**Issue by trungams** [idoneam/Canary#92]
### Description of Problem / Inefficiency:

Most of the web scraping we're currently doing is by sending http requests to another website and parse the html, json response. While using python's `requests` library is not too bad, it often blocks the bot from doing other operations, creating a delay if someone wants to call another command. One way to improve is to make the functions async where possible.

### Implementation Suggestion:

Use `aiohttp` client for http requests

### Additional Context / Screenshots:

- `aiohttp` official documentation: https://docs.aiohttp.org/en/stable/
- Check this blog post for a comparison between `requests` and `aiohttp` modules http://mahugh.com/2017/05/23/http-requests-asyncio-aiohttp-vs-requests/

**Comment by idodin** [comment]
[Grequests](https://github.com/kennethreitz/grequests) is another asynchronous requests module. From my brief look, it seems easier to use than aiohttp (no need to directly handle the asyncio event loop).

**Comment by trungams** [comment]
Closed in #104

**Comment by trungams** [comment]
mb. changes still in dev
